
version: "3"

volumes:
  data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    expose:
      - 8000
    ports:
      -8000:8000
    restart: unless-stopped
    volumes: 
      - data:/app/data
    